name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - tqdm
  - pip:
    - torch==1.12.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
    - torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
    - torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116
    - opencv-python
    - joblib
